### ISSUE TITLE
Can you tell me which code is this project Original?

### ISSUE THREAD

**Issue by sulinhuang** [frederickjansen/flac-as3#2]
i want to fix the play 24bit 96khz level5 flac noise bug.

**Comment by frederickjansen** [comment]
You mean which project is this code based on? It's not based on an existing implementation. I just used [libFLAC](https://github.com/oneman/libflac) for the CRC table, the [FLAC format specification](https://xiph.org/flac/format.html) as the reference to base my code on, and finally the [Python Audiotools Reference](https://sourceforge.net/projects/audiotools/files/audio%20formats%20reference/2.20/), which was absolutely invaluable to understand the nuances of FLAC that are not properly explained in the reference documentation.

Please let me know if you fix the bug, I'd be happy to merge your code! This was an old hobby project of mine and could definitely use quite a bit of refactoring.
